### ISSUE TITLE
Workflow Failed - Speedwagon

### ISSUE THREAD

**Issue by vbjohna** [UIUCLibrary/Speedwagon#479]
Henry, 
I was trying to OCR via Speedwagon and got the following error

Traceback (most recent call last):
  File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\speedwagon\workflows\workflow_ocr.py", line 367, in read_image
    resulting_text = reader.read(file)
                     ^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\uiucprescon\ocr\reader.py", line 76, in read
    image = tesseractwrap.load_image(file)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uiucprescon.ocr.tesseractwrap.TesseractGlueException: Unknown exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\speedwagon\runner_strategies.py", line 649, in run_job_on_thread
    task.exec()
  File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\speedwagon\tasks\tasks.py", line 186, in exec
    TaskStatus.FAILED if not self.work() else TaskStatus.SUCCESS
                             ^^^^^^^^^^^
  File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\speedwagon\workflows\workflow_ocr.py", line 337, in work
    resulting_text = self.read_image(self._source, self._lang)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\speedwagon\workflows\workflow_ocr.py", line 369, in read_image
    raise SpeedwagonException(f"Unable to read {file}") from error
speedwagon.exceptions.SpeedwagonException: Unable to read U:/HTIngest/WomenPrintersBoundwith\99536247412205899\access\99536247412205899-00000001.jp2

![image](https://github.com/UIUCLibrary/Speedwagon/assets/144837926/6987a37a-d2ca-4967-90ba-b92f34267292)

**Comment by henryborchers** [comment]
@vbjohna have you looked at U:/HTIngest/WomenPrintersBoundwith\99536247412205899\access\99536247412205899-00000001.jp2 to make sure the file isn't corrupted?

**Comment by vbjohna** [comment]
As far as I can tell this file is fine. I was ablet open it with adobe reader. Is there another way to see if it corrupt?

> @vbjohna have you looked at U:/HTIngest/WomenPrintersBoundwith\99536247412205899\access\99536247412205899-00000001.jp2 to make sure the file isn't corrupted?

As far as I can tell this file is fine. I was ablet open it with adobe reader. Is there another way to see if it corrupt?

**Comment by vbjohna** [comment]
It is an MMSID-0000000X file that its not correct. Im gonna try to rereun it and see what happens.

**Comment by vbjohna** [comment]
I reran it and so far so good

**Comment by henryborchers** [comment]
@vbjohna can I close this issue then?

**Comment by vbjohna** [comment]
Yes

Johna Von Behrens
________________________________
